version = "1.0.*"
upstream_repository = "https://github.com/psf/palworld-save-tools"
requires = ["palworld-save-tools>=0.19.0"]
extra_description = """\
    Note: `palworld-save-tools-stubs` has required `palworld-save-tools>=0.19.0` since v1.0.0. \
    """

[tool.stubtest]
extras = ["socks"]
